apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: rsa-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: frankisinfotech/arca-pg-personal-project-rsa-encryption-service:1  # Replace with your actual image name and tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command: ["uvicorn", "app.main:app", "--reload", "--host=0.0.0.0", "--port=8000"]
