apiVersion: v1
kind: Namespace
metadata:
  name: arca-payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsa-encryption-service
  namespace: arca-payment-service
spec:
  selector:
    matchLabels:
      app: rsa-encryption-service 
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: rsa-encryption-service 
    spec:
      containers:
      - name: rsa-encryption-service
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 200Mi
             cpu: 0.5
#         env:
#         - name: SPRING_PROFILES_ACTIVE
#           value: production-microservice
        imagePullPolicy: Always
#         readinessProbe:
#           httpGet:
#             path: /healthz
#             port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rsa-encryption-service-svc
  namespace: arca-payment-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: rsa-encryption-service

  ports:
    - name: http
      port: 80
 

  type: ClusterIP
