apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: rsa-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
