apiVersion: v1
kind: Service
metadata:
  name: rsa-encryption-service
  namespace: arca-payment-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
